### ISSUE TITLE
Idea: skip decoding big `ValueNodes`

### ISSUE THREAD

**Issue by moreal** [planetarium/NineChronicles.Snapshot#238]
This issue is for ideas for improving inefficiencies in snapshots.

By far the most time-consuming feature of Snapshot is CopyStates. And a big part of that is the Bencodex decoding process. There are a lot of big states in 9C. Avatar, inventory, and so on. Those big states are also what makes things slow in the actual action logic. But since snapshots don't need to calculate states, it's obviously better to avoid decoding if you can. So this idea proposes a way to avoid decoding.

CopyStates is the process of traversing the Merkle tree and putting key-value pairs into a new RocksDB. Libplanet's merkle tree consists of the four nodes below.

- Node: HashNode | ValueNode | ShortNode | FullNode
- HashNode: Binary(=bytes) (inline) (32 bytes)
- ValueNode: List[Null, Value]
- ShortNode: List[Binary path, Node] (The Node part is only included inline if the Node is smaller than the size of the HashNode, the path part is in the form of nibbles, so the keying method of FungibleAssetValue is the maximum length. The maximum is 2*2*(len("_") + Address.Size + len("_") + SHA1.Size) => 168 bytes. Unless a new keying scheme emerges)
- FullNode: List[HashNode | ValueNode][len=17] (ValueNodes are only included inline if they are smaller than the size of the HashNode; the size of the Bencodex List when all are HashNodes is (HashNode.Size + len("32:")) * 17 + len("le") => 597 bytes)

When I described the nodes above, I also mentioned their size. The FullNode can have the largest value, and its size is 597 bytes. Any other larger value must be a ValueNode. As we said above, the snapshot is not obligated to decode the ValueNode - if it's larger than 597 bytes, let's skip it!

Why couldn't we avoid decoding before? If you ask me, I have to tell you about the situation when I was optimizing at the time. At the time, Libplanet was also worried about state size, and we added IndirectValue to the Bencodex to reduce duplicate values while still allowing us to operate as a Merkle tree. As a result, we couldn't be sure which node was which based on the size of simple bytes. I had to load all the values into the loader, and then I was able to copy the IndirectValue bypass representation just fine.

To summarize, the idea is that if you don't have any IndirectValues in your store, any value with a size greater than 597 bytes can be considered a value node and skip decoding.

(Translated by DeepL)

-----

이 이슈는 스냅샷의 비효율적인 부분을 개선하기 위한 아이디어를 적어놓은 이슈입니다.

스냅샷의 기능 중 가장 시간을 많이 소모하는 곳은 단연 CopyStates 입니다. 그리고 그 중에는 Bencodex 디코딩 과정이 많은 지분을 차지합니다. 9c의 상태들은 큼직한 것들이 많습니다. 아바타, 인벤토리 따위가 그런 예입니다. 그런 큰 상태들은 실제 액션 로직에서도 느린 속도를 만드는 요인이기도 합니다. 하지만 스냅샷은 상태를 계산할 필요까지는 없기 때문에 디코딩을 피할수만 있다면 피하는 것이 당연히 좋습니다. 그래서 이 아이디어에서는 디코딩을 피하는 방법을 제안합니다.

CopyStates는 머클 트리를 순회하면서 key-value 쌍을 새로운 RocksDB에 Put하는 과정입니다. Libplanet의 머클트리는 아래 4가지 노드로 구성되어 있습니다.

- Node: HashNode | ValueNode | ShortNode | FullNode
- HashNode: Binary(=bytes) (inline) (32 bytes)
- ValueNode: List[Null, Value]
- ShortNode: List[Binary path, Node] (Node부분은 Node가 HashNode의 크기보다 작을때만 인라인으로 포함됩니다, path 부분은 nibbles 형태로 되어있으니 FungibleAssetValue의 키 방식이 최대 길이 입니다. 최대 2 * 2 * (len("_") + Address.Size + len("_") + SHA1.Size) => 168 bytes입니다. 만약 새로운 키 방식이 등장하지 않는다면요)
- FullNode: List[HashNode | ValueNode][len=17] (ValueNode는 HashNode의 크기보다 작을때만 인라인으로 포함됩니다, 모두 HashNode일때 Bencodex List의 크기는 (HashNode.Size + len("32:")) * 17 + len("le") => 597 bytes 입니다)

위 노드들 설명하면서 크기도 같이 부연 설명을 했습니다. 보다 시피 FullNode가 가장 큰 값을 지닐 수 있고 그 크기는 597 bytes 입니다. 그 외에 더 큰 값은 필히 ValueNode 일 것 입니다. 위에서 말했듯이 스냅샷은 굳이 ValueNode를 디코딩할 의무가 없습니다. 597 bytes 이상이라면 디코딩을 스킵합시다!

이전에는 왜 디코딩을 피할 수 없었나요? 라는 질문이 온다면 제가 당시 최적화를 할 때의 상황을 이야기 해야할 것 같습니다. 당시에 Libplanet 쪽에서도 상태 크기 관련해서 걱정이 많았고 Bencodex에 IndirectValue를 추가하며 중복 값을 줄이면서도 머클 트리로 운영할 수 있게 하는 기능을 추가했었습니다. 그렇게 되니 단순 bytes의 크기 만으로 어떤 노드인지 확신할 수 없었습니다. Loader로 모든 값들을 불러와야지만 IndirectValue 우회 표현된 값들도 온전히 잘 복사할 수 있었습니다.

요약하면, 만약 스토어에 아무런 IndirectValue가 없는 상태라면, 597 bytes 이상의 크기를 가진 value들은 value node로 간주하고 디코딩을 건너뛰어도 된다는 아이디어 입니다.

**Comment by moreal** [comment]
It's not a measured value in an environment where other factors are well isolated, but it's there for the record. The 7862778th block took about 32 minutes with only CopyStates behavior in the tip-in store. With the above suggestions, it took 11 minutes, which is about a third less time.

(Translated by DeepL)
---------

다른 요소들이 잘 배제된 환경에서 측정된 값은 아니지만 기록 상 남깁니다. 7862778번째 블록이 Tip인 스토어에서 CopyStates 동작만 했을때 약 32분이 소요 되었습니다. 위 제안사항을 적용하였을때는 11분이 소요되었고 이는 약 1/3 정도로 소요시간을 줄일수 있을 것으로 보입니다.

**Comment by moreal** [comment]
Applying this idea with bencodex-go, running 4 writers and 30 workers in parallel took 7 minutes and 12 seconds.

(Translated by DeepL)

------

bencodex-go로 이 아이디어 적용해서 writer 4개, worker 30개 병렬로 돌렸을 때 7분 12초 소요.

**Comment by area363** [comment]
This update has been applied via https://github.com/planetarium/NineChronicles.Snapshot/pull/239 (latest libplanet bump). Thank you @moreal 🙇
